org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.234
loader_version_range=[2,)

mod_id=redonestorage
mod_name=Redone Storage
mod_license=MIT
mod_version=6.0.0-alpha.6
mod_group_id=net.gigabit101.redonestorage
mod_authors=CombatCody95; based on original work by Modmuss50 and Gigabit101
mod_description=Redone Storage adds large storage disks, a multiblock autocrafter, and extended wireless tools for Refined Storage.
