name: Feature request
description: Suggest an improvement for Redone Storage
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed feature
      description: Explain how you think the feature should work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
